name: test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: go test ./... -coverprofile=coverage.out
      - name: Report coverage.out
        uses: k1LoW/octocov-action@v0
